This notebook is part of my [Python data science curriculum](http://www.terran.us/articles/python_curriculum.html)

## Chapter 2 Exercises

In [1]:
import numpy as np
import scipy as sp

This document uses the ["collapsible headings" extension from nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/collapsible_headings/readme.html).  If you have that extension installed, you will see that the "solution" sections start collapsed, and you can expand them and look at them _after_ doing the exercise yourself.  I also recommend the "toc2" extension.

I also tried the "exercise2" extension, but it had unacceptable bugs (the solution became irretrievable if I inserted a new cell right below the collapsed exercise).

## Exercise
Make a 12-long array of consecutive integers from 1 to 12, inclusive:

## Solution

In [2]:
a1=np.array(np.arange(1,13),dtype='int32')
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

## Exercise
Make a 12-long array of floating point numbers between 0 and 1:

## Solution

In [3]:
a2=np.array(np.arange(0,1+1/11,1/11))
a2

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

## Exercise
Add them together.  What is the type of the result?

## Solution

In [4]:
(a1+a2).dtype

dtype('float64')

## Exercise
Take your 1d array of integers and transform it into a row vector, then transform it into a column vector.

## Solution

In [5]:
# Row:
a1[np.newaxis,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]], dtype=int32)

In [6]:
# Column:
np.vstack(a1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int32)

In [7]:
# One more approach, which will do either:
a1.reshape(12, 1)
# Or, if you don't want to hardcode the size:
a1.reshape(a1.shape[0], 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int32)

## Exercise

Using your array of integers, create a "multiplication table" (2d array where each cell is the product of its axis indices).  Do this in two different ways.  One way should use the row and column matrix versions, and the other should not

## Solution

In [8]:
np.multiply.outer(a1,a1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]],
      dtype=int32)

In [9]:
a1[:,np.newaxis] @ a1[np.newaxis,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]],
      dtype=int32)

In [10]:
# Note a subtlety here - in Python, @ does matrix multiplication, and * does "broadcasting",
# which is always the outer product, regardless of whether the row or column comes first:

rowv = a1[np.newaxis,0:4]
colv = a1[0:4,np.newaxis]
print("row * column")
print(rowv * colv)
print("column * row")
print(colv * rowv)

print("row @ column")
print(rowv @ colv)
print("column @ row")
print(colv @ rowv)
# In older versions you had to use numpy.dot or numpy.matmul instead of infix @.  They behave
# differently in dimensions greater than two.

row * column
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
column * row
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
row @ column
[[30]]
column @ row
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [11]:
# Unlike matrix multiplication, in Python, you can also broadcast non-multiplicative operations:

rowv - colv

array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [-2, -1,  0,  1],
       [-3, -2, -1,  0]], dtype=int32)

## Exercise
Compute the factorial of 12 by reducing your array.  Now compute it with the Numpy factorial function.  Use ipython timing magic functions to see which is faster.

## Solution

In [12]:
print(np.multiply.reduce(a1))
%timeit np.multiply.reduce(a1)

479001600
3.54 µs ± 124 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
print(np.math.factorial(12))
%timeit np.math.factorial(12)

479001600
174 ns ± 6.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## Exercise

In Python, is a 1d vector taken as a row or column vector for broadcasting purposes?  What about for matrix multiplication?

## Solution

In [14]:
# For broadcasting, they are effectively rows, because broadcasting pads on the left:
colv * np.full(4,1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [18]:
# For matrix multiplication, they're not exactly either:
print("row by 1d:")
print(rowv @ np.full(4,1))

print("\n1d by row:")
try:
  print(np.full(4,1) @ rowv)
except Exception as e:
  print(repr(e))

row by 1d:
[10]

1d by row:
ValueError('shapes (4,) and (1,4) not aligned: 4 (dim 0) != 1 (dim 0)')


## Exercise
Create an array of normal random numbers.  Sort the original array in order of decreasing absolute value.

## Solution

In [16]:
n=np.random.normal(size=20)
n[(-(n*n)).argsort()]

array([-2.49073165,  2.39633395, -2.04363117, -1.66539244,  1.27749369,
       -1.25198296, -0.83854892, -0.78263418, -0.62685332, -0.5671522 ,
       -0.39794515, -0.29073459,  0.2352208 , -0.20088277,  0.16662046,
        0.16407303, -0.11810839, -0.11593318,  0.10746925,  0.06451154])